## Task 1:
-In this task, we are going to practice data cleaning.

In [73]:
import pandas as pd

In [75]:
df = pd.read_csv("3) Sentiment dataset.csv")

In [77]:
df

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,728,732,Collaborating on a science project that receiv...,Happy,2017-08-18 18:20:00,ScienceProjectSuccessHighSchool,Facebook,#ScienceFairWinner #HighSchoolScience,20.0,39.0,UK,2017,8,18,18
728,729,733,Attending a surprise birthday party organized ...,Happy,2018-06-22 14:15:00,BirthdayPartyJoyHighSchool,Instagram,#SurpriseCelebration #HighSchoolFriendship,25.0,48.0,USA,2018,6,22,14
729,730,734,Successfully fundraising for a school charity ...,Happy,2019-04-05 17:30:00,CharityFundraisingTriumphHighSchool,Twitter,#CommunityGiving #HighSchoolPhilanthropy,22.0,42.0,Canada,2019,4,5,17
730,731,735,"Participating in a multicultural festival, cel...",Happy,2020-02-29 20:45:00,MulticulturalFestivalJoyHighSchool,Facebook,#CulturalCelebration #HighSchoolUnity,21.0,43.0,UK,2020,2,29,20
731,732,736,Organizing a virtual talent show during challe...,Happy,2020-11-15 15:15:00,VirtualTalentShowSuccessHighSchool,Instagram,#VirtualEntertainment #HighSchoolPositivity,24.0,47.0,USA,2020,11,15,15

## Types of columns

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    object
 3   Sentiment     732 non-null    object
 4   Timestamp     732 non-null    object
 5   User          732 non-null    object
 6   Platform      732 non-null    object
 7   Hashtags      732 non-null    object
 8   Retweets      732 non-null    float64
 9   Likes         732 non-null    float64
 10  Country       732 non-null    object
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: float64(2), int64(6), object(7)
memory usage: 85.9+ KB

## Change "Retweets" and "likes" columns types from float to integer

In [83]:
df = df.astype({"Retweets": int, "Likes": int})

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    object
 3   Sentiment     732 non-null    object
 4   Timestamp     732 non-null    object
 5   User          732 non-null    object
 6   Platform      732 non-null    object
 7   Hashtags      732 non-null    object
 8   Retweets      732 non-null    int32
 9   Likes         732 non-null    int32
 10  Country       732 non-null    object
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: int32(2), int64(6), object(7)
memory usage: 80.2+ KB

## Change "Timestamp" column type from object to datetime

In [88]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    object
 3   Sentiment     732 non-null    object
 4   Timestamp     732 non-null    datetime64[ns]
 5   User          732 non-null    object
 6   Platform      732 non-null    object
 7   Hashtags      732 non-null    object
 8   Retweets      732 non-null    int32
 9   Likes         732 non-null    int32
 10  Country       732 non-null    object
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: datetime64[ns](1), int32(2), int64(6), object(6)
memory usage: 80.2+ KB

## Drop "Unnamed: 0.1", "Unnamed: 0", "Year", "Month", "Day", "Hour" columns

In [92]:
df_droped_columns = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'Year', 'Month', 'Day', 'Hour'])

In [98]:
df_droped_columns

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country
0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15,30,USA
1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5,10,Canada
2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20,40,USA
3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8,15,UK
4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12,25,Australia
...,...,...,...,...,...,...,...,...,...
727,Collaborating on a science project that receiv...,Happy,2017-08-18 18:20:00,ScienceProjectSuccessHighSchool,Facebook,#ScienceFairWinner #HighSchoolScience,20,39,UK
728,Attending a surprise birthday party organized ...,Happy,2018-06-22 14:15:00,BirthdayPartyJoyHighSchool,Instagram,#SurpriseCelebration #HighSchoolFriendship,25,48,USA
729,Successfully fundraising for a school charity ...,Happy,2019-04-05 17:30:00,CharityFundraisingTriumphHighSchool,Twitter,#CommunityGiving #HighSchoolPhilanthropy,22,42,Canada
730,"Participating in a multicultural festival, cel...",Happy,2020-02-29 20:45:00,MulticulturalFestivalJoyHighSchool,Facebook,#CulturalCelebration #HighSchoolUnity,21,43,UK
731,Organizing a virtual talent show during challe...,Happy,2020-11-15 15:15:00,VirtualTalentShowSuccessHighSchool,Instagram,#VirtualEntertainment #HighSchoolPositivity,24,47,USA

In [100]:
df_droped_columns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Text       732 non-null    object
 1   Sentiment  732 non-null    object
 2   Timestamp  732 non-null    datetime64[ns]
 3   User       732 non-null    object
 4   Platform   732 non-null    object
 5   Hashtags   732 non-null    object
 6   Retweets   732 non-null    int32
 7   Likes      732 non-null    int32
 8   Country    732 non-null    object
dtypes: datetime64[ns](1), int32(2), object(6)
memory usage: 45.9+ KB

## Sort columns by "Timestamp" column in ascending order

In [104]:
df_sort_time = df_droped_columns.sort_values(by = "Timestamp", ascending = True)

In [106]:
df_sort_time

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country
109,"Revisiting old memories, feeling a sense of e...",Elation,2010-05-15 15:30:00,NostalgiaFan,Twitter,#Elation #Memories,20,40,Canada
124,Contentment in the simplicity of a quiet Sund...,Contentment,2010-08-15 10:00:00,SimpleJoys,Twitter,#Contentment #SundayMood,30,60,Australia
151,Contentment in the embrace of a loved one. ...,Contentment,2010-11-12 20:20:00,LovingEmbrace,Twitter,#Contentment #Love,30,60,India
111,"Embracing the beauty of nature, a moment of c...",Contentment,2011-06-20 14:45:00,NatureLover2,Facebook,#Contentment #Nature,25,50,India
152,Serenity found in the beauty of a sunset by t...,Serenity,2011-07-22 18:30:00,SunsetWatcher2,Instagram,#Serenity #SunsetViews,22,45,Canada
...,...,...,...,...,...,...,...,...,...
720,Attending a school talent show to support clas...,Happy,2023-10-18 16:45:00,TalentShowSupportHighSchool,Facebook,#TalentShow #HighSchoolEntertainment,19,38,Canada
721,Exploring a new hiking trail with friends over...,Happy,2023-10-19 18:20:00,WeekendHikeHighSchool,Instagram,#NatureAdventures #HighSchoolFriends,21,42,UK
722,Winning a friendly sports competition against ...,Happy,2023-10-20 14:15:00,SportsVictoryHighSchool,Twitter,#SportsTriumph #HighSchoolAthletics,26,50,USA
723,Receiving a heartfelt letter from a pen pal in...,Happy,2023-10-21 17:30:00,PenPalConnectionHighSchool,Facebook,#GlobalFriendship #HighSchoolCorrespondence,23,45,Canada
724,Creating a beautiful mural with fellow art ent...,Happy,2023-10-22 20:45:00,MuralCreationHighSchool,Instagram,#ArtCollaboration #HighSchoolCreativity,22,43,UK

## Reset index to arrange them in ascending order

In [30]:
df_index = df_sort_time.reset_index()

In [32]:
df_index

,index,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country
0,109,"Revisiting old memories, feeling a sense of e...",Elation,2010-05-15 15:30:00,NostalgiaFan,Twitter,#Elation #Memories,20,40,Canada
1,124,Contentment in the simplicity of a quiet Sund...,Contentment,2010-08-15 10:00:00,SimpleJoys,Twitter,#Contentment #SundayMood,30,60,Australia
2,151,Contentment in the embrace of a loved one. ...,Contentment,2010-11-12 20:20:00,LovingEmbrace,Twitter,#Contentment #Love,30,60,India
3,111,"Embracing the beauty of nature, a moment of c...",Contentment,2011-06-20 14:45:00,NatureLover2,Facebook,#Contentment #Nature,25,50,India
4,152,Serenity found in the beauty of a sunset by t...,Serenity,2011-07-22 18:30:00,SunsetWatcher2,Instagram,#Serenity #SunsetViews,22,45,Canada
...,...,...,...,...,...,...,...,...,...,...
727,720,Attending a school talent show to support clas...,Happy,2023-10-18 16:45:00,TalentShowSupportHighSchool,Facebook,#TalentShow #HighSchoolEntertainment,19,38,Canada
728,721,Exploring a new hiking trail with friends over...,Happy,2023-10-19 18:20:00,WeekendHikeHighSchool,Instagram,#NatureAdventures #HighSchoolFriends,21,42,UK
729,722,Winning a friendly sports competition against ...,Happy,2023-10-20 14:15:00,SportsVictoryHighSchool,Twitter,#SportsTriumph #HighSchoolAthletics,26,50,USA
730,723,Receiving a heartfelt letter from a pen pal in...,Happy,2023-10-21 17:30:00,PenPalConnectionHighSchool,Facebook,#GlobalFriendship #HighSchoolCorrespondence,23,45,Canada
731,724,Creating a beautiful mural with fellow art ent...,Happy,2023-10-22 20:45:00,MuralCreationHighSchool,Instagram,#ArtCollaboration #HighSchoolCreativity,22,43,UK

## We have a problem! An "index" column is created out of nowhere, now we are going to drop this column

In [111]:
df_sort_index = df_index.drop(columns=['index'])

In [113]:
df_sort_index

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country
0,"Revisiting old memories, feeling a sense of e...",Elation,2010-05-15 15:30:00,NostalgiaFan,Twitter,#Elation #Memories,20,40,Canada
1,Contentment in the simplicity of a quiet Sund...,Contentment,2010-08-15 10:00:00,SimpleJoys,Twitter,#Contentment #SundayMood,30,60,Australia
2,Contentment in the embrace of a loved one. ...,Contentment,2010-11-12 20:20:00,LovingEmbrace,Twitter,#Contentment #Love,30,60,India
3,"Embracing the beauty of nature, a moment of c...",Contentment,2011-06-20 14:45:00,NatureLover2,Facebook,#Contentment #Nature,25,50,India
4,Serenity found in the beauty of a sunset by t...,Serenity,2011-07-22 18:30:00,SunsetWatcher2,Instagram,#Serenity #SunsetViews,22,45,Canada
...,...,...,...,...,...,...,...,...,...
727,Attending a school talent show to support clas...,Happy,2023-10-18 16:45:00,TalentShowSupportHighSchool,Facebook,#TalentShow #HighSchoolEntertainment,19,38,Canada
728,Exploring a new hiking trail with friends over...,Happy,2023-10-19 18:20:00,WeekendHikeHighSchool,Instagram,#NatureAdventures #HighSchoolFriends,21,42,UK
729,Winning a friendly sports competition against ...,Happy,2023-10-20 14:15:00,SportsVictoryHighSchool,Twitter,#SportsTriumph #HighSchoolAthletics,26,50,USA
730,Receiving a heartfelt letter from a pen pal in...,Happy,2023-10-21 17:30:00,PenPalConnectionHighSchool,Facebook,#GlobalFriendship #HighSchoolCorrespondence,23,45,Canada
731,Creating a beautiful mural with fellow art ent...,Happy,2023-10-22 20:45:00,MuralCreationHighSchool,Instagram,#ArtCollaboration #HighSchoolCreativity,22,43,UK

## Now we need to process the data to find out if there is data that need to be cleaned or not

In [115]:
df_sort_index.isnull().sum()

Text         0
Sentiment    0
Timestamp    0
User         0
Platform     0
Hashtags     0
Retweets     0
Likes        0
Country      0
dtype: int64

## There are no nulls

In [117]:
df_sort_index.duplicated().sum()

20

## There are 20 duplicated data

In [125]:
df_drop_duplicate = df_sort_index.drop_duplicates()

In [127]:
df_drop_duplicate

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country
0,"Revisiting old memories, feeling a sense of e...",Elation,2010-05-15 15:30:00,NostalgiaFan,Twitter,#Elation #Memories,20,40,Canada
1,Contentment in the simplicity of a quiet Sund...,Contentment,2010-08-15 10:00:00,SimpleJoys,Twitter,#Contentment #SundayMood,30,60,Australia
2,Contentment in the embrace of a loved one. ...,Contentment,2010-11-12 20:20:00,LovingEmbrace,Twitter,#Contentment #Love,30,60,India
3,"Embracing the beauty of nature, a moment of c...",Contentment,2011-06-20 14:45:00,NatureLover2,Facebook,#Contentment #Nature,25,50,India
4,Serenity found in the beauty of a sunset by t...,Serenity,2011-07-22 18:30:00,SunsetWatcher2,Instagram,#Serenity #SunsetViews,22,45,Canada
...,...,...,...,...,...,...,...,...,...
727,Attending a school talent show to support clas...,Happy,2023-10-18 16:45:00,TalentShowSupportHighSchool,Facebook,#TalentShow #HighSchoolEntertainment,19,38,Canada
728,Exploring a new hiking trail with friends over...,Happy,2023-10-19 18:20:00,WeekendHikeHighSchool,Instagram,#NatureAdventures #HighSchoolFriends,21,42,UK
729,Winning a friendly sports competition against ...,Happy,2023-10-20 14:15:00,SportsVictoryHighSchool,Twitter,#SportsTriumph #HighSchoolAthletics,26,50,USA
730,Receiving a heartfelt letter from a pen pal in...,Happy,2023-10-21 17:30:00,PenPalConnectionHighSchool,Facebook,#GlobalFriendship #HighSchoolCorrespondence,23,45,Canada
731,Creating a beautiful mural with fellow art ent...,Happy,2023-10-22 20:45:00,MuralCreationHighSchool,Instagram,#ArtCollaboration #HighSchoolCreativity,22,43,UK

## There are 712 rows now, we need to reset index

In [129]:
df_sort_index1 = df_drop_duplicate.reset_index()

In [131]:
df_sort_index1

,index,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country
0,0,"Revisiting old memories, feeling a sense of e...",Elation,2010-05-15 15:30:00,NostalgiaFan,Twitter,#Elation #Memories,20,40,Canada
1,1,Contentment in the simplicity of a quiet Sund...,Contentment,2010-08-15 10:00:00,SimpleJoys,Twitter,#Contentment #SundayMood,30,60,Australia
2,2,Contentment in the embrace of a loved one. ...,Contentment,2010-11-12 20:20:00,LovingEmbrace,Twitter,#Contentment #Love,30,60,India
3,3,"Embracing the beauty of nature, a moment of c...",Contentment,2011-06-20 14:45:00,NatureLover2,Facebook,#Contentment #Nature,25,50,India
4,4,Serenity found in the beauty of a sunset by t...,Serenity,2011-07-22 18:30:00,SunsetWatcher2,Instagram,#Serenity #SunsetViews,22,45,Canada
...,...,...,...,...,...,...,...,...,...,...
707,727,Attending a school talent show to support clas...,Happy,2023-10-18 16:45:00,TalentShowSupportHighSchool,Facebook,#TalentShow #HighSchoolEntertainment,19,38,Canada
708,728,Exploring a new hiking trail with friends over...,Happy,2023-10-19 18:20:00,WeekendHikeHighSchool,Instagram,#NatureAdventures #HighSchoolFriends,21,42,UK
709,729,Winning a friendly sports competition against ...,Happy,2023-10-20 14:15:00,SportsVictoryHighSchool,Twitter,#SportsTriumph #HighSchoolAthletics,26,50,USA
710,730,Receiving a heartfelt letter from a pen pal in...,Happy,2023-10-21 17:30:00,PenPalConnectionHighSchool,Facebook,#GlobalFriendship #HighSchoolCorrespondence,23,45,Canada
711,731,Creating a beautiful mural with fellow art ent...,Happy,2023-10-22 20:45:00,MuralCreationHighSchool,Instagram,#ArtCollaboration #HighSchoolCreativity,22,43,UK

In [133]:
df_sort_index2 = df_sort_index1.drop(columns=['index'])

In [135]:
df_sort_index2

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country
0,"Revisiting old memories, feeling a sense of e...",Elation,2010-05-15 15:30:00,NostalgiaFan,Twitter,#Elation #Memories,20,40,Canada
1,Contentment in the simplicity of a quiet Sund...,Contentment,2010-08-15 10:00:00,SimpleJoys,Twitter,#Contentment #SundayMood,30,60,Australia
2,Contentment in the embrace of a loved one. ...,Contentment,2010-11-12 20:20:00,LovingEmbrace,Twitter,#Contentment #Love,30,60,India
3,"Embracing the beauty of nature, a moment of c...",Contentment,2011-06-20 14:45:00,NatureLover2,Facebook,#Contentment #Nature,25,50,India
4,Serenity found in the beauty of a sunset by t...,Serenity,2011-07-22 18:30:00,SunsetWatcher2,Instagram,#Serenity #SunsetViews,22,45,Canada
...,...,...,...,...,...,...,...,...,...
707,Attending a school talent show to support clas...,Happy,2023-10-18 16:45:00,TalentShowSupportHighSchool,Facebook,#TalentShow #HighSchoolEntertainment,19,38,Canada
708,Exploring a new hiking trail with friends over...,Happy,2023-10-19 18:20:00,WeekendHikeHighSchool,Instagram,#NatureAdventures #HighSchoolFriends,21,42,UK
709,Winning a friendly sports competition against ...,Happy,2023-10-20 14:15:00,SportsVictoryHighSchool,Twitter,#SportsTriumph #HighSchoolAthletics,26,50,USA
710,Receiving a heartfelt letter from a pen pal in...,Happy,2023-10-21 17:30:00,PenPalConnectionHighSchool,Facebook,#GlobalFriendship #HighSchoolCorrespondence,23,45,Canada
711,Creating a beautiful mural with fellow art ent...,Happy,2023-10-22 20:45:00,MuralCreationHighSchool,Instagram,#ArtCollaboration #HighSchoolCreativity,22,43,UK

In [143]:
df_sort_index2['Country'].value_counts().reset_index()

                  Country  count
0                     USA     59
1                    USA      51
2                      UK     49
3                  Canada     44
4              Australia      36
..                    ...    ...
110      Switzerland           1
111              Jamaica       1
112    Japan                   1
113          Japan             1
114   India                    1

[115 rows x 2 columns]

## Japan and USA is repeated 2 times

## We are going to combine the USA and Japan repeated rows with each other by removing any line spaces between variations of countries

In [145]:
df_sort_index2['Country'] = df_sort_index2['Country'].str.strip()

In [154]:
df_sort_index2['Country'].value_counts().reset_index()

           Country  count
0              USA    184
1               UK    140
2           Canada    132
3        Australia     70
4            India     68
5           Brazil     17
6           France     16
7            Japan     15
8          Germany     14
9            Italy     11
10    South Africa      6
11          Greece      5
12           Spain      5
13     Netherlands      4
14         Denmark      2
15        Portugal      2
16          Sweden      2
17  Czech Republic      2
18     Switzerland      2
19         Belgium      2
20        Thailand      1
21        Colombia      1
22           Kenya      1
23         Jamaica      1
24        Maldives      1
25         Ireland      1
26          Norway      1
27         Austria      1
28            Peru      1
29           China      1
30        Cambodia      1
31        Scotland      1
32          Jordan      1

## USA, UK and Canada are the most repeated countries in the table, English speaking countries have a huge share in the table

In [157]:
df_sort_index2

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country
0,"Revisiting old memories, feeling a sense of e...",Elation,2010-05-15 15:30:00,NostalgiaFan,Twitter,#Elation #Memories,20,40,Canada
1,Contentment in the simplicity of a quiet Sund...,Contentment,2010-08-15 10:00:00,SimpleJoys,Twitter,#Contentment #SundayMood,30,60,Australia
2,Contentment in the embrace of a loved one. ...,Contentment,2010-11-12 20:20:00,LovingEmbrace,Twitter,#Contentment #Love,30,60,India
3,"Embracing the beauty of nature, a moment of c...",Contentment,2011-06-20 14:45:00,NatureLover2,Facebook,#Contentment #Nature,25,50,India
4,Serenity found in the beauty of a sunset by t...,Serenity,2011-07-22 18:30:00,SunsetWatcher2,Instagram,#Serenity #SunsetViews,22,45,Canada
...,...,...,...,...,...,...,...,...,...
707,Attending a school talent show to support clas...,Happy,2023-10-18 16:45:00,TalentShowSupportHighSchool,Facebook,#TalentShow #HighSchoolEntertainment,19,38,Canada
708,Exploring a new hiking trail with friends over...,Happy,2023-10-19 18:20:00,WeekendHikeHighSchool,Instagram,#NatureAdventures #HighSchoolFriends,21,42,UK
709,Winning a friendly sports competition against ...,Happy,2023-10-20 14:15:00,SportsVictoryHighSchool,Twitter,#SportsTriumph #HighSchoolAthletics,26,50,USA
710,Receiving a heartfelt letter from a pen pal in...,Happy,2023-10-21 17:30:00,PenPalConnectionHighSchool,Facebook,#GlobalFriendship #HighSchoolCorrespondence,23,45,Canada
711,Creating a beautiful mural with fellow art ent...,Happy,2023-10-22 20:45:00,MuralCreationHighSchool,Instagram,#ArtCollaboration #HighSchoolCreativity,22,43,UK